### ISSUE TITLE
Module causes problems with MIUI camera app [Lavender]

### ISSUE THREAD

**Issue by Msprg** [Kyliekyler/PIXELARITY#1]
I have a rom by MIUIos.cz on my Redmi note 7 [Lavender] installed, along with magisk and PIXELARITY module of course.

I noticed, that when the PIXELARITY module is active, stock MIUI cam app starts misbehaving. For example some functions and camera modes get disabled, entering into panorama mode guarantees crash, and entering setings in camera app, not always, but often causes crash as well.

Is this somehow fixable? I am able to provide desired logs on demand.

**Comment by Kyliekyler** [comment]
This should be fixed rn

**Comment by Msprg** [comment]
I just tested the new version of PIXELARITY, and the issues I describe, are unfortunately still present. Camera app is missing functions and when switched to panorama mode, crashes immediately.
Are you willing to look into it?

btw, my rom was detected as xiaomi.eu, but these roms are very similiar, so I do not think this poses any issue right now.

**Comment by Kyliekyler** [comment]
Oh yes, I figured it out, I have the same problem as before. It was the camera 2 api props. I will look on to it.
